### ISSUE TITLE
Excel 2010 ribbon Add-in with ASIM not visible

### ISSUE THREAD

**Issue by mandano** [thinkOfaNumber/Asim#2]
Hi,

i installed the ASIM program as described in the quick install guide (with msi installer) and activated your add-in. Excel states that it is running. The ribbon Add-in is activated, under options. But it is not visible. So i cant work with it. Maybe it is a microsoft problem?
It is a windows 7 pc (64bit) with excel 2010, everything is up to date. 
I m not quite sure what info to post else to give you better possibility to debug. But i m keen to give you more infos.

**Comment by thinkOfaNumber** [comment]
Hi mandano,

Can you see an add-in ribbon tab at all? On mine, the order of tabs is Home, Insert, Page Layout, Formulas, Data, Review, View, Developer, **Add-Ins**, and Team.  When you select the Add-Ins tab, there should be an Asim drop-down box.

If not, in excel options > customise ribbon, make sure the Add-Ins main tab is checked.

Let me know if this helps.

**Comment by DWA1970** [comment]
Thx Iain,

Long-time no contact, how you’re well.  Nice to see another user trying it out.

Thx

Dow

**Comment by mandano** [comment]
Hi thinkOfaNumber,

thx for your reply. I cant see a addin ribbon at all. Every other addin i activate integrates itself elsewhere, but not in the ribbon addin. I did activate/checked the ribbon addin in the excel option: customize ribbon.
My order of ribbons is similair to the one you described. I can activate oder deactivate other ribbons, but not the addin ribbon.

**Comment by mandano** [comment]
hopefully i'll can try this on an other computer soon, so its maybe something specific with this computer...:)

**Comment by thinkOfaNumber** [comment]
Hi mandano, could you please send me a screenshot of the "Customise ribbon" window? something like this: 
![image](https://cloud.githubusercontent.com/assets/5110983/7760085/e6266a5a-0056-11e5-81c5-5de27986f5f7.png)

thanks

**Comment by mandano** [comment]
![1](https://cloud.githubusercontent.com/assets/11614702/7799849/191c1f74-030c-11e5-9f9e-16c51a675ec3.png)
![2](https://cloud.githubusercontent.com/assets/11614702/7799850/191f1e36-030c-11e5-976f-5d1c4741f083.png)

its german, but one can see hopefully that it is activated.

**Comment by thinkOfaNumber** [comment]
Hi,

Just to confirm that you've done this step, if you click on the "Gehe zu..." button next to Excel-Add-Ins, is ASIM checked as in this dialog box?
![image](https://cloud.githubusercontent.com/assets/5110983/7835385/a80fe038-04b7-11e5-96f5-dfd23a6578ee.png)

I see ASIM installed as follows:
![image](https://cloud.githubusercontent.com/assets/5110983/7835402/d7d5bd9c-04b7-11e5-8b51-abc536361da1.png)

Finally if that doesn't work, can you please confirm you're using Version 2.2.4?

From this step onwards, I would need to get access to a German copy of Windows and Excel to try and debug further.

**Comment by mandano** [comment]
hi thinkofaNumber,

thanks again for your help and afford. Yes i m using 2.2.4. Here are the screenshots.

![1](https://cloud.githubusercontent.com/assets/11614702/7859734/d824412e-0543-11e5-9702-168df8800497.png)
![3](https://cloud.githubusercontent.com/assets/11614702/7859827/59c2c62e-0544-11e5-94bf-fec2bb30c536.png)


Best regards.

**Comment by mandano** [comment]
do you think that it would be useful for me to buy the english language package?

**Comment by thinkOfaNumber** [comment]
The English language package for Windows or Office?  It may help, but I can't guarantee it.  You can contact PowerWater and ask for support for ASIM and they can hire me to do the work. Do you know anyone there? It would be difficult for me to debug though as I presume I'd have to install the German windows and German Office.

Can you get a hold of a trial English windows version?  You can download virtual machines from Microsoft for limited use here: http://dev.modern.ie/tools/vms/#downloads.  Let me know if you're able to try the english version.

Sorry I can't solve it easily!
