### ISSUE TITLE
Example Hybrid Data files

### ISSUE THREAD

**Issue by paraus** [thinkOfaNumber/Asim#3]
I can't seem to find the Asim Example Load.csv, Asim Example PV.csv, ScaleLoad.csv files for the PV/Diesel configuration example. Would you be able to upload them so that I can have a reference as to the formatting required for Asim?  
REF (pg 9, Configuration Guide)

**Comment by thinkOfaNumber** [comment]
Hi,

if you install ASIM you'll find some sample data in this location: %LOCALAPPDATA%\C:\Users\iain.buchanan\AppData\Local\Apps\Asim\Samples\load.zip

I understand that you might not want to install it just to browse the samples, so I've uploaded some files that I used in the configuration guide.  Please see the release for the file "ASIM.Example.Input.Data.zip": https://github.com/thinkOfaNumber/Asim/releases/tag/v2.2.4
